presto-cli-hive -e "insert into ibsdb.quality select 'ybrz_count' as type, c_ydz_spcode as spcode,count(1) as value,data_format(current_timestamp - interval '1' day,'yyyyMMdd') as day from original.t_qxrz where day=data_format(current_timestamp - interval '1' day,'yyyyMMdd') group by c_ydz_spcode;"
presto-cli-hive -e "insert into ibsdb.quality select 'ybrz_msisdn' as type, c_ydz_spcode as spcode,count(1) as value,data_format(current_timestamp - interval '1' day,'yyyyMMdd') as day from original.t_qxrz where day=data_format(current_timestamp - interval '1' day,'yyyyMMdd') and c_msisdn != '' group by c_ydz_spcode;"
presto-cli-hive -e "insert into ibsdb.quality select 'ybrz_imsi' as type, c_ydz_spcode as spcode,count(1) as value,data_format(current_timestamp - interval '1' day,'yyyyMMdd') as day from original.t_qxrz where day=data_format(current_timestamp - interval '1' day,'yyyyMMdd') and c_imsi != '' group by c_ydz_spcode;"
presto-cli-hive -e "insert into ibsdb.quality select 'ybrz_imei' as type, c_ydz_spcode as spcode,count(1) as value,data_format(current_timestamp - interval '1' day,'yyyyMMdd') as day from original.t_qxrz where day=data_format(current_timestamp - interval '1' day,'yyyyMMdd') and c_imei != '' group by c_ydz_spcode;"
presto-cli-hive -e "insert into ibsdb.quality select 'ybrz_three_code' as type, c_ydz_spcode as spcode,count(1) as value,data_format(current_timestamp - interval '1' day,'yyyyMMdd') as day from original.t_qxrz where day=data_format(current_timestamp - interval '1' day,'yyyyMMdd') and c_msisdn != '' and c_imei != '' and c_imsi != '' group by c_ydz_spcode;"
presto-cli-hive -e "insert into ibsdb.quality select 'ybrz_three_code_empty' as type, c_ydz_spcode as spcode,count(1) as value,data_format(current_timestamp - interval '1' day,'yyyyMMdd') as day from original.t_qxrz where day=data_format(current_timestamp - interval '1' day,'yyyyMMdd') and c_msisdn = '' and c_imei = '' and c_imsi = '' group by c_ydz_spcode;"
presto-cli-hive -e "insert into ibsdb.quality select 'ybrz_msisdn_distinct' as type, c_ydz_spcode as spcode,count(distinct c_msisdn) as value,data_format(current_timestamp - interval '1' day,'yyyyMMdd') as day from original.t_qxrz where day=data_format(current_timestamp - interval '1' day,'yyyyMMdd') and c_msisdn != '' group by c_ydz_spcode;"
presto-cli-hive -e "insert into ibsdb.quality select 'ybrz_uli' as type, c_ydz_spcode as spcode,count(1) as value,data_format(current_timestamp - interval '1' day,'yyyyMMdd') as day from original.t_qxrz where day=data_format(current_timestamp - interval '1' day,'yyyyMMdd') and c_ydz_uli != '' group by c_ydz_spcode;"

presto-cli-hive -e "insert into ibsdb.quality select 'ybrz_http' as type, c_ydz_spcode as spcode,count(1) as value,data_format(current_timestamp - interval '1' day,'yyyyMMdd') as day from original.t_qxrz where day=data_format(current_timestamp - interval '1' day,'yyyyMMdd') and c_network_proto = '42' group by c_ydz_spcode;"

presto-cli-hive -e "insert into ibsdb.quality select 'ybrz_url' as type, c_ydz_spcode as spcode,count(1) as value,data_format(current_timestamp - interval '1' day,'yyyyMMdd') as day from original.t_qxrz where day=data_format(current_timestamp - interval '1' day,'yyyyMMdd') and c_url != '' group by c_ydz_spcode;"
presto-cli-hive -e "insert into ibsdb.quality select 'ybrz_busstype' as type, c_ydz_spcode as spcode,count(1) as value,data_format(current_timestamp - interval '1' day,'yyyyMMdd') as day from original.t_qxrz where day=data_format(current_timestamp - interval '1' day,'yyyyMMdd') and c_busstype >0 group by c_ydz_spcode;"
presto-cli-hive -e "insert into ibsdb.quality select 'ybrz_sip' as type, c_ydz_spcode as spcode,count(1) as value,data_format(current_timestamp - interval '1' day,'yyyyMMdd') as day from original.t_qxrz where day=data_format(current_timestamp - interval '1' day,'yyyyMMdd') and c_sip != '' group by c_ydz_spcode;"
presto-cli-hive -e "insert into ibsdb.quality select 'ybrz_dip' as type, c_ydz_spcode as spcode,count(1) as value,data_format(current_timestamp - interval '1' day,'yyyyMMdd') as day from original.t_qxrz where day=data_format(current_timestamp - interval '1' day,'yyyyMMdd') and c_dip != '' group by c_ydz_spcode;"

presto-cli-hive -e "insert into ibsdb.quality select 'ybrz_l5' as type, c_ydz_spcode as spcode,count(1) as value,data_format(current_timestamp - interval '1' day,'yyyyMMdd') as day from original.t_qxrz where day=data_format(current_timestamp - interval '1' day,'yyyyMMdd') and c_l5_proto in (1,2,3,4,5,6,7,8,9,10,11,12) group by c_ydz_spcode;"
presto-cli-hive -e "insert into ibsdb.quality select 'ybrz_spcode' as type, 4 as spcode,count(1) as value,data_format(current_timestamp - interval '1' day,'yyyyMMdd') as day from original.t_qxrz where day=data_format(current_timestamp - interval '1' day,'yyyyMMdd') and c_ydz_spcode not in (1,2,3);"
presto-cli-hive -e "insert into ibsdb.quality select 'ybrz_areacode' as type,c_ydz_spcode as spcode,count(1) as value,data_format(current_timestamp - interval '1' day,'yyyyMMdd') as day from original.t_qxrz where day=data_format(current_timestamp - interval '1' day,'yyyyMMdd') and c_ydz_areacode > 99999 group by c_ydz_spcode;"
presto-cli-hive -e "insert into ibsdb.quality select 'ybrz_homecode' as type,c_ydz_spcode as spcode,count(1) as value,data_format(current_timestamp - interval '1' day,'yyyyMMdd') as day from original.t_qxrz where day=data_format(current_timestamp - interval '1' day,'yyyyMMdd') and c_ydz_homecode > 99999 group by c_ydz_spcode;"


